server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/mywebapp.access.log;

    location /health {
        return 404;
    }

    location / {
        proxy_pass http://unix:/run/mywebapp.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}